### PR TITLE
fix: ensure correct application shutdown with forRootAsync and multiple databases

### PR DESCRIPTION
**Pull request by tsangste**
When using `forRootAsync` module with multiple databases on application shutdown it fails to find MikroORM and causes a shutdown error.

NOTE: I tried to make a test for this in [mikro-orm.middleware.test.ts](https://github.com/mikro-orm/nestjs/compare/master...tsangste:root_async_close_failing?expand=1#diff-d86ddb6702e051052d6e0bdc3d2362a4fbcc3b5bc7a2491545244b6fcc401f6b) but it seems the `AfterAll` lifecycle is swallowing the error and unsure if its a configuration issue as on other projects I've seen `AfterAll` fail on errors

### CODE REVIEW

**Comment by B4nan** [comment]
Thanks! The changes in lock file look weird, can you remove those please?

**Comment by tsangste** [comment]
> Thanks! The changes in lock file look weird, can you remove those please?

Sure can do! I just did a `yarn install`

**Comment by tsangste** [comment]
hold on the PR for a sec found a bug

**Comment by B4nan** [comment]
Weird that an install would alter lock file. I will rebuild it when releasing and update deps if needed.

**Comment by tsangste** [comment]
> Weird that an install would alter lock file. I will rebuild it when releasing and update deps if needed.

It could of been done with me trying to get sqlite working on this machine which stopped me from running the tests.

I have also resolved the bug 👍

**Comment by B4nan** [comment]
Last time I had sqlite build issues installing node gyp as a dev dep explicitly helped. I can add that too, but I dont want to mix it with other changes in one PR.

**Pull request merged**
