### PR TITLE
feat: added entities serialization interceptor

### PR DESCRIPTION
**Pull request by H6LS1S**
https://github.com/mikro-orm/nestjs/issues/37

### CODE REVIEW

**Comment by mareksuscak** [comment]
I just tested this approach and it works pretty well so far. I wonder if we should use `toObject` rather than `toPOJO`. There are minor differences between the two.

**Comment by mareksuscak** [comment]
@H6LS1S when this new interceptor is used together with `ClassSerializerInterceptor`, are `class-transformer` decorators such as `@Expose` and `@Exclude` supposed to work?

**Comment by sualko** [comment]
Would be nice if this could be reopened, because without this mikro-orm and nestjs can't work together.

**Comment by mareksuscak** [comment]
For anyone finding this issue, take a look at Automapper if you're okay with explicit mapping as it has support for NestJS and Mikro ORM via an officially supported adapter: https://automapperts.netlify.app/docs/nestjs

**Pull request closed without merging**
